# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload metadata to Google Play"
  lane :metadata do
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      sync_image_upload: true,
    )
  end

  desc "Deploy a new version to Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
